the one for the small rock

diff --git a/getem b/getem
--- a/getem
+++ b/getem
@@ -55,7 +55,19 @@ set -e
 echo "------------------------------------------"
 echo "Running dump.go..."
 echo
-go build -o dumper dump.go
+rebuild=1
+if [[ -f "dumper" ]]; then
+    read -p "Found pre-existing 'dumper' binary (built from dump.go). Rebuild? (y/n)? " choice
+    case "$choice" in
+      y|Y ) echo ;;
+      n|N ) echo "Skipping rebuild of dump.go -> ./dumper ..." && echo && rebuild=0;;
+      * ) echo "Invalid choice." && exit 1;;
+    esac
+fi
+if [[ rebuild -eq 1 ]]; then
+    echo "> go build -o dumper dump.go ..."
+    go build -o dumper dump.go
+fi
 ./dumper
 # rm ./dump
 # go run dump.go
